[package]
name = "proclog"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9"
internment = "0.8"
ariadne = "0.4"
crossterm = "0.27"
ratatui = { path = "vendor/ratatui" }
clap = { version = "4.5", features = ["derive"] }
notify = "6"

[dev-dependencies]
