[workspace]
members = [
    "crates/proclog",
    "crates/proclog-cli",
]
resolver = "2"

[workspace.dependencies]
chumsky = "0.9"
internment = "0.8"
crossterm = "0.27"
ratatui = { path = "vendor/ratatui" }
clap = { version = "4.5", features = ["derive"] }
notify = "6"
