[package]
name = "proclog-ast"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde", "internment/serde"]

[dependencies]
internment = { workspace = true }
serde = { version = "1.0", features = ["derive"], optional = true }
