[package]
name = "proclog"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { workspace = true }
internment = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
splr = "0.17.2"
