[package]
name = "proclog-core"
version = "0.1.0"
edition = "2021"

[features]
test-utils = []

[dependencies]
proclog-ast = { path = "../proclog-ast" }

[dev-dependencies]
internment = { workspace = true }
